new file replace

diff --git a/docker-jenkins-lab1/Jenkinsfile b/docker-jenkins-lab1/Jenkinsfile
--- a/docker-jenkins-lab1/Jenkinsfile
+++ b/docker-jenkins-lab1/Jenkinsfile
@@ -1,11 +1,13 @@
 pipeline {
     agent any
+
     environment {
         IMAGE_NAME = "myapp-lab1"
         CONTAINER_NAME = "myapp-lab1-container"
     }
 
     stages {
+
         stage('Checkout') {
             steps {
                 checkout scm
@@ -16,25 +18,39 @@ pipeline {
             steps {
                 sh 'docker build -t $IMAGE_NAME .'
             }
-        } 
+        }
 
         stage('Run Container') {
             steps {
                 sh '''
-                docker rm -f $CONTAINER_NAME || true
-                docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME
+                    docker rm -f $CONTAINER_NAME || true
+                    docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME
                 '''
             }
         }
+
+        stage('Test Container') {
+            steps {
+                sh '''
+                    sleep 5
+                    curl -f http://localhost:5000/health
+                '''
+            }
+        }
+
+    }
+
     post {
         always {
             sh 'docker rm -f $CONTAINER_NAME || true'
         }
+
         success {
             echo 'Build and test succeeded'
         }
+
         failure {
-            echo 'Build  failed. check logs above'
+            echo 'Build failed. Check logs above.'
         }
     }
 }
